### ISSUE TITLE
Add support for nested directories and modules

### ISSUE THREAD

**Issue by bjd2385** [bjd2385/dynamic-continuation-orb#10]
## Describe Request:

Add support for nested directories with modules, so we can target subdirectories/paths like

```
terraform/development/
terraform/production/
```

## Examples:

N/A

## Supporting Documentation Links:

N/A

**Comment by gnaryak** [comment]
Hi @bjd2385 - fwiw, I'd appreciate this feature. It would be helpful to be able to use dynamic-continuation-orb with a monorepo directory structure like:

- apps/
--- app1
--- app2
- packages/
--- pkg1
--- pkg2

This approach is documented nicely by Robin Wieruch at https://www.robinwieruch.de/javascript-monorepos/
Thanks!

**Comment by bjd2385** [comment]
@gnaryak I just published an update that I've tested pretty thoroughly since last night. Let me know if you have any issues, happy to help.

**Comment by gnaryak** [comment]
Hey, that's great. Thanks, @bjd2385 ! It'll be really nice to be able to use an optimal hierarchical directory structure in our monorepo. We are incorporating this into our documented best practices.

It may be a week or three before we are at a place to be able to give it a thorough test but we are pointed in that direction. I'll reach out if I have any feedback.

Thanks!

**Comment by bjd2385** [comment]
@jalgraves this fix adds a feature I think you requested many months ago.
