### ISSUE TITLE
circleci config validate failing

### ISSUE THREAD

**Issue by gnaryak** [bjd2385/dynamic-continuation-orb#24]
## Orb version 

3.4.0

## What happened

The pipeline fails at the step "CircleCI config validate reduced config"

The offending command is:
circleci config validate .circleci/continue-config.yml --org-slug bitbucket/$CIRCLE_ORGANIZATION --token $CIRCLE_TOKEN --skip-update-check

The error message is:
Error: Unable to validate config: Permission denied

## Expected behavior

The validation should succeed. 😝 

## Additional Information

I reran the job with SSH and learned:

- The env vars seem to be properly set.
- The command succeeds without the --org-slug parameter.
- I tried a bunch of different values for --org-slug but couldn't get any of them to work. "bitbucket/{organization id from organization settings}". "bitbucket/{my personal bitbucket username}". Even "github/bjd2385".
- I swapped --org-id for --org-slug and that worked.

Is --org-slug really necessary? Could we omit it, or use --org-id instead? If --org-slug is truly necessary, any idea about what I should put there?

Thanks!!!!!

### config.yml

version: 2.1

setup: true

orbs:
  dynamic: bjd2385/dynamic-continuation@3.4.0

workflows:
  on-push:
    jobs:
      - dynamic/continue:
          context: orb-publishing-studio-async
          project-type: bitbucket
          modules: |
            /services/studio-async-job

**Comment by bjd2385** [comment]
Sorry I didn't reply sooner @gnaryak ! So to break this down for myself, it looks like this is presently evaluated as
```
circleci config validate << parameters.continue-config >> --org-slug << parameters.project-type >>/<< parameters.circle-organization >> --token << parameters.circle-token >> --skip-update-check
```
v
```
circleci config validate .circleci/continue-config.yml --org-slug github/bjd2385 --token $CIRCLE_TOKEN --skip-update-check
```
You can get the org slug from the URL in your browser as well. May I ask if you were able to fix this? Sounds like it could be a bad API token or... I could always add the ability to use either org-slug or org-id.

**Comment by gnaryak** [comment]
Hi Emma - I ended up implementing continuation without using the orb. As I experimented and tinkered, I also ran into what seemed to me to be an intractable problem. If I change multiple projects in my monorepo, the CI/CD can only run for one of them if we use continuation in the way that this orb is implemented. I ended up having one CircleCI config that sets variables based on the files that have changed, and then a second mega-config file that processes all of the changed projects.

That second config file will grow to be awkwardly big but I am able to successfully use conditionals in it to only run the appropriate parts of workflows based on the files and projects that have been changed.

I love the architecture of the orb you have created. Simple, clean, extensible. But I didn't see how it would be able to handle changes to multiple projects in the monorepo.

Thanks, cheers,
Andrew

**Comment by bjd2385** [comment]
> ... I also ran into what seemed to me to be an intractable problem. If I change multiple projects in my monorepo, the CI/CD can only run for one of them if we use continuation in the way that this orb is implemented.

Interesting, and glad you were able to find a solution! I am curious/interested in learning more about the part above, but I'll go ahead and close this for now. Always open to extending this project to suite additional real-world use cases.
