### ISSUE TITLE
Breaking due to infinite recursion install bug with CircleCI CLI

### ISSUE THREAD

**Issue by yangchoo** [bjd2385/dynamic-continuation-orb#59]
The `Install CircleCI CLI` step is currently failing. See https://github.com/CircleCI-Public/circleci-cli/issues/941 for context.

A potential workaround is pinning the version but that currently fails due to https://github.com/CircleCI-Public/circleci-cli-orb/issues/13. Its not clear to me whether the repository is being maintained given that the PR has been up for a while.

I see two main options here:
1. Wait for CircleCI CLI team to merge and publish a fix.
2. Hotfix this orb by replacing the `circleci/install` call. I.e. Copy the fixed version of the script that respects the VERSION parameter (from the PR linked above) and use that in-place of the call.

This is breaking some builds for me, so I'll prefer 2, but I understand that requires some additional resources and increases the maintenance surface area.

**Comment by Joshua-Igoni** [comment]
This is also affecting me as well from using this orb

**Comment by yangchoo** [comment]
@Joshua-Igoni fyi this should be resolved now. They've fixed the upstream circleci-cli issue. 

I'm going to close this issue. There is still a longer-term issue but ideally that'll be fixed by https://github.com/CircleCI-Public/circleci-cli-orb/issues/13 now that there's more visibility

**Comment by bjd2385** [comment]
I didn't see this. I've since hit issues with the CLI, also, so I've pinned the version as of several releases ago.
