### ISSUE TITLE
allow config validation when using a private orb

### ISSUE THREAD

**Issue by dtomlinson91** [bjd2385/dynamic-continuation-orb#81]
First want to say thanks so much for providing this orb. It greatly reduces our complexity with monolithic repos and speeds up build times (and saves a shit ton of £££) - it's really underrated!

I am trying to move all our re-usable Circle commands/jobs into a private orb to use internally, however the validate stage is failing when I try to use the orb with your dynamic continuation:

```
#!/bin/bash -eo pipefail
circleci config validate .circleci/continue-config.yml

Error: config compilation contains errors: [{Cannot find a***e/data-***-ops-orb@0.1.3 in the orb registry. Check that the namespace, orb name and version are correct.}]

Exited with code exit status 255

CircleCI received exit code 255
```

It looks like CircleCI have a support article on how you can validate a config that uses a private orb here: <https://support.circleci.com/hc/en-us/articles/10643012267291-How-to-validate-a-config-that-uses-private-Orbs> - it looks like an easy addition? The organisation is already set with an env var. I'm not sure if the API token used for this orb would necessarily have the permission to view the orb, in our case it does but this might not be the case?

**Comment by bjd2385** [comment]
Haha, glad it's proving to be of some use!

And thanks for the link. It looks like we just need to (optionally?) pass the org slug and token that's already provided / required to validate it ~

https://github.com/bjd2385/dynamic-continuation-orb/blob/v3.6.10/src/jobs/continue.yml#L179

That command's probably only good for public orb validation, correct. That's a simple addition.

**Comment by bjd2385** [comment]
I've cut v3.6.11 with this fix @dtomlinson91, let me know if doesn't solve this problem.

**Comment by dtomlinson91** [comment]
Working perfectly, thank you so much ❤️
